# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   annotations:
# #     kompose.cmd: kompose convert
# #     kompose.version: 1.22.0 (955b78124)
# #   creationTimestamp: null
# #   labels:
# #     io.kompose.service: jaeger
# #   name: jaeger
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:  
# #       io.kompose.service: jaeger
# #   strategy: {}
# #   template:
# #     metadata:
# #       annotations:
# #         kompose.cmd: kompose convert
# #         kompose.version: 1.22.0 (955b78124)
# #         sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
# #         sidecar.istio.io/statsInclusionRegexps: http.*
# #       creationTimestamp: null
# #       labels:
# #         io.kompose.service: jaeger
# #     spec:
# #       containers:
# #         - image: jaegertracing/all-in-one:latest
# #           name: hotel-reserv-jaeger
# #           ports:
# #             - containerPort: 14269
# #             - containerPort: 5778
# #             - containerPort: 14268
# #             - containerPort: 14267
# #             - containerPort: 16686
# #             - containerPort: 5775
# #               protocol: UDP
# #             - containerPort: 6831
# #               protocol: UDP
# #             - containerPort: 6832
# #               protocol: UDP
# #           resources:
# #             requests:
# #               cpu: 100m
# #             limits:
# #               cpu: 1000m
# #       restartPolicy: Always
# # status: {}


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: kompose convert
#     kompose.version: 1.22.0 (955b78124)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: jaeger
#   name: jaeger
# spec:
#   replicas: 1
#   selector:
#     matchLabels:  
#       io.kompose.service: jaeger
#   strategy: {}
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: kompose convert
#         kompose.version: 1.22.0 (955b78124)
#         sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
#         sidecar.istio.io/statsInclusionRegexps: http.*
#       creationTimestamp: null
#       labels:
#         io.kompose.service: jaeger
#     spec:
#       containers:
#         - image: jaegertracing/all-in-one:latest
#           name: hotel-reserv-jaeger
#           env:
#             - name: COLLECTOR_ZIPKIN_HOST_PORT
#               value: ":9411"
#             - name: COLLECTOR_OTLP_ENABLED
#               value: "true"
#             - name: SPAN_STORAGE_TYPE
#               value: "memory"
#             - name: QUERY_BASE_PATH
#               value: "/"
#           ports:
#             - containerPort: 14269
#             - containerPort: 5778
#             - containerPort: 14268
#             - containerPort: 14267
#             - containerPort: 16686
#             - containerPort: 5775
#               protocol: UDP
#             - containerPort: 6831
#               protocol: UDP
#             - containerPort: 6832
#               protocol: UDP
#             - containerPort: 9411
#             - containerPort: 4317
#               name: otlp-grpc
#             - containerPort: 4318
#               name: otlp-http
#           resources:
#             requests:
#               cpu: 100m
#             limits:
#               cpu: 1000m
#       restartPolicy: Always
# status: {}



apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: jaeger
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:  
      io.kompose.service: jaeger
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      labels:
        io.kompose.service: jaeger
    spec:
      hostNetwork: true  # Use host network so services can connect via localhost
      containers:
        - image: jaegertracing/all-in-one:latest
          name: hotel-reserv-jaeger
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: SPAN_STORAGE_TYPE
              value: "memory"
            - name: QUERY_BASE_PATH
              value: "/"
            - name: COLLECTOR_OTLP_GRPC_ENABLED
              value: "true"
          ports:
            - containerPort: 14269
            - containerPort: 5778
            - containerPort: 14268
            - containerPort: 14267
            - containerPort: 16686
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 9411
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
      restartPolicy: Always
status: {}